### ISSUE TITLE
HMAC for the 'case where blocksz < hashsz'

### ISSUE THREAD

**Issue by adfernandes** [ctz/cifra#1]
In line 44 of `cifra/src/hmac.c`, there is an `assert(nkey <= hash->blocksz)` because that case is not covered by the standard.

It kind-of depends _which_ standard. :smile:

While that case is not covered in [RFC-2104](https://tools.ietf.org/html/rfc2104), it **is** covered in [FIPS-198-1](http://csrc.nist.gov/publications/fips/fips198-1/FIPS-198-1_final.pdf). (Basically, you just zero-pad, as you would naïvely expect.)

Sorry for no patch, but I wrote my own C++ code and came upon your (awesome!) repo while hunting around.

Cheers!

**Comment by ctz** [comment]
Hm, interesting.

FIPS-191-1, section 4, 'Step 2' says:

> If the length of K > B: hash K to obtain an L byte string, then append (B-L)
> zeros to create a B-byte string K0 (i.e., K0 = H(K) || 00...00). Go to step 4.

Say we have a theoretical hash function with |B|=32, |H|=64. We start with a key longer than the block size to trigger this clause, and hash the key. Now we have a |H(K)| > |B|, and want to append 32-64 = -32 bytes to make a full block.

I'm going to shuffle the code around to make it clearer when the assert will fire: on a crazy hash function.

Cheers,
Joe
