### ISSUE TITLE
Don't copy key into cf_chacha20_ctx

### ISSUE THREAD

**Issue by microwavesafe** [ctz/cifra#13]
I was poking through the chacha20 implementation and noticed that the key is copied into the ```cf_chacha20_ctx``` struct at key0 and key1

https://github.com/ctz/cifra/blob/cfa6df9ca0007abe3c70409d02b3779ac1742297/src/chacha20.c#L126

or

https://github.com/ctz/cifra/blob/cfa6df9ca0007abe3c70409d02b3779ac1742297/src/chacha20.c#L137

I am trying to avoid copying the key into RAM as the MCU protection level I'm implementing doesn't stop a debugger reading out RAM, but does prevent reading out flash. I can't go to the next level as this will disable field upgrades and prevent me from fixing security bugs.

If the key0 and key1 were pointers, instead of copying the key, this would prevent a debugger gaining access to the key, they would only be able to access the address, with the positive side effect of reducing RAM. I can't see any reason why this would break the code otherwise, but it will have an impact on users of the library that rely on this copy.

I should be able to manage a pull request, but would a change like this be accepted? Or is there some issue I'm over looking?

**Comment by microwavesafe** [comment]
For chacha20 I think the only changes you would need are

salsa20.h
```
typedef struct
{
  const uint8_t *key0;
  const uint8_t *key1;
  uint8_t nonce[16];
  const uint8_t *constant;
  uint8_t block[64];
  size_t nblock;
  size_t ncounter;
} cf_salsa20_ctx, cf_chacha20_ctx;
```
chacha20.c
```
static void set_key(cf_chacha20_ctx *ctx, const uint8_t *key, size_t nkey)
{
  switch (nkey)
  {
    case 16:
      ctx->key0 = key;
      ctx->key1 = key;
      ctx->constant = chacha20_tau;
      break;
    case 32:
      ctx->key0 = key;
      ctx->key1 = key + 16;
      ctx->constant = chacha20_sigma;
      break;
    default:
      abort();
  }
}
```
However you would need similar changes to salsa20.c ```cf_salsa20_init``` function, unless we split the struct definition.

**Comment by yumkam** [comment]
I'd like to note that while it is not exactly documented, but currently you can call `cf_chacha20_init()` and do anything with memory pointed by key. With proposed change implemented, you must not touch it (overwrite, `free()`, `return` from function if it is on the stack, etc) before you are done with this cipher context.
